### PR TITLE
feat(979): use launcher script as entrypoint command BREAKING CHANGE: entrypoint change 

### PR DESCRIPTION
**Pull request by tk3fftk**
This PR provides same fixes as https://github.com/screwdriver-cd/executor-k8s/pull/85

Dependent Launcher PR screwdriver-cd/launcher#179
Related issue: screwdriver-cd/screwdriver#979

### CODE REVIEW

**Comment by tk3fftk** [comment]
It's still broken with the error.
```
 (HTTP code 400) unexpected - OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/opt/sd/launcher_entrypoint.sh\": stat /opt/sd/launcher_entrypoint.sh: no such file or directory": unknown
```

**Comment by minz1027** [comment]
@tk3fftk what version of launcher did you use to test it? need to have this line in the launcher version: https://github.com/screwdriver-cd/launcher/blob/master/Dockerfile#L85

**Comment by tk3fftk** [comment]
@minz1027 I used latest version of launcher on the day (may be `v5.0.4`).
```
$ docker image list | grep launcher
screwdrivercd/launcher                                latest              66f973a07608        4 days ago          311MB
```

**Comment by minz1027** [comment]
@tk3fftk Can you try this to see if that file exists under `/opt/sd`?`docker run -it --entrypoint "/bin/sh" screwdrivercd/launcher:v5.0.4`? And also make sure you're not using Docker 18. With Docker 18, there can be missing files.

**Pull request merged**
